name: Reusable Workflow
on:
  push:
    branches:
      - main
jobs:
  use-replace-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use main workflow
        run: |
          # Use the workflow keyword to call the replace-tag workflow
          workflow "Replace Tag Workflow" {
            uses = "./.github/workflows/replace-tag.yml"
          }
  use-build-and-push:
    runs-on: ubuntu-latest
    needs: use-replace-tag
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use build-and-push workflow
        run: |
          # Use the workflow keyword to call the build-and-push workflow
          workflow "Build and Push Workflow" {
            uses = "./.github/workflows/build-push-docker.yml"
          }



