name: Reusable Workflow
on:
  push:
    branches:
      - main
jobs:
  use-replace-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use main workflow
        uses: ./.github/workflows/replace-tag.yml
  use-build-and-push:
    runs-on: ubuntu-latest
    needs: use-replace-tag
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use build-and-push workflow
        uses: ./.github/workflows/build-push-docker.yml



