name: Reusable Workflow
on:
  push:
    branches:
      - main
jobs:
  use-reusable:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use main workflow
        uses: ./replace-tag
  build-and-push:
    runs-on: ubuntu-latest
    needs: use-reusable  
    steps:
      - name: Build and Push Docker Image
        uses: ./build-push-docker



