name: Reusable Workflow
on:
  push:
    branches:
      - main
jobs:
  use-reusable:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use main workflow
        uses: ./.github/workflows/replace-tag.yml
  build-and-push:
    runs-on: ubuntu-latest
    needs: use-reusable  # Specify the dependency on the "use-reusable" job
    steps:
      - name: Build and Push Docker Image
        uses: ./.github/workflows/build-push-docker.yml



