name: Reusable Workflow
on:
  push:
    branches:
      - main
jobs:
  use-reusable:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use main workflow
        uses: ./main.yml
  build-and-push:
    runs-on: ubuntu-latest
    needs: use-reusable  # Specify the dependency on the "replace-string" job
    steps:
      - name: Call build-push workflow
        uses: ./build-push-docker.yml
