name: Reusable Workflow
on:
  push:
    branches:
      - main
jobs:
  use-replace-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Replace strings in file
        uses: MathieuSoysal/replace-string-in-file@v1.0.0
        with:
          file: sample-file.txt
          old-string: "tag 1"
          new-string: "tag 2"

      - name: Stage changes
        uses: EndBug/add-and-commit@v7
        with:
          message: "Replace 'tag 1' with 'tag 2' in sample-file.txt"
          author_name: ${{ secrets.repo_owner }}
          author_email: ${{ secrets.repo_owner_email }}

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          
  use-build-and-push:
    runs-on: ubuntu-latest
    needs: use-replace-tag
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download modified file artifact
        uses: actions/download-artifact@v2
        with:
          name: modified-file
          path: sample-modified-file.txt

      - name: Update Dockerfile
        run: |
          echo "COPY sample-modified-file.txt /usr/local/app/modified-file.txt" >> Dockerfile

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.repo_owner }}
          password: ${{ secrets.PAT }}

      - name: Push Docker image to GHCR
        run: docker push ghcr.io/${{ secrets.repo_owner }}/greenbone-task:latest

      


